export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Solutions } from './Solutions'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'
